---
sudo: required
language: python
python: "2.7"

install:
  - pip install ansible

  # Add ansible.cfg to pick up roles path.
  - "{ echo '[defaults]'; echo 'roles_path = ../'; } >> ansible.cfg"

script:
  # Syntax Check
  - ansible-playbook -i localhost, tests/test.yaml --syntax-check

  # Run tests
  - ansible-playbook -i localhost, --connection=local --become tests/test.yaml

  # Idempotence test
  - >
    ansible-playbook -i localhost, --connection=local --become tests/test.yaml
    | grep -q 'changed=0.*failed=0'
    && (echo 'Idempotence test: pass' && exit 0)
    || (echo 'Idempotence test: fail' && exit 1)
