---

- name: Manage ~/.ssh/authorized_keys for generic user(s)
  authorized_key:
    user: "{{item.0.name}}"
    key: "{{item.1.key}}"
    state: "{{ item.1.state }}"
    path: "{{ item.0.home | default('/home/' + item.0.name) }}/.ssh/authorized_keys"
  with_subelements:
    - "{{ users }}"
    - ssh_key
    - skip_missing: yes

- name: Manage ~/.ssh/authorized_keys for host specific user(s)
  authorized_key:
    user: "{{item.0.name}}"
    key: "{{item.1.key}}"
    state: "{{ item.1.state }}"
    path: "{{ item.0.home | default('/home/' + item.0.name) }}/.ssh/authorized_keys"
  with_subelements:
    - "{{ host_specific_users }}"
    - ssh_key
    - skip_missing: yes

- name: Manage ~/.ssh/authorized_keys for group specific user(s)
  authorized_key:
    user: "{{item.0.name}}"
    key: "{{item.1.key}}"
    state: "{{ item.1.state }}"
    path: "{{ item.0.home | default('/home/' + item.0.name) }}/.ssh/authorized_keys"
  with_subelements:
    - "{{ group_specific_users }}"
    - ssh_key
    - skip_missing: yes
