---

# Create groups
- name: Create Groups
  group:
    name: "{{ item.key }}"
    gid: "{{ item.value.gid | default(omit) }}"
    system: "{{ item.value.system | default(omit) }}"
    state: "{{ item.value.state }}"
  loop: "{{ users_groups|dict2items }}"
  when:
    - item.value.state is defined
    - item.value.state != "absent"

# Remove groups
- name: Remove Groups
  group:
    name: "{{ item.value }}"
    state: absent
  loop: "{{ users_groups|dict2items }}"
  when:
    - item.value.state is defined
    - item.value.state == "absent"
