---

# Create groups
- name: Create Groups
  ansible.builtin.group:
    name: "{{ item.key }}"
    gid: "{{ item.value.gid | default(omit) }}"
    system: "{{ item.value.system | default(omit) }}"
    state: "{{ item.value.state }}"
  loop: "{{ users_groups | dict2items }}"
  when:
    - item.value.state is defined
    - item.value.state != "absent"
  no_log: "{{ users_no_log | bool }}"

# Remove groups
- name: Remove Groups
  ansible.builtin.group:
    name: "{{ item.value }}"
    state: absent
  loop: "{{ users_groups | dict2items }}"
  when:
    - item.value.state is defined
    - item.value.state == "absent"
  no_log: "{{ users_no_log | bool }}"
