---

# Load a bit specific defaults
- name: Load OS specific values
  include_vars: "{{ var_files }}"
  when: var_files|bool
  vars:
    var_files: '{{ lookup("first_found", files=files, errors="ignore") }}'
    files:
      - "{{ ansible_distribution }}.yml"
      - "{{ ansible_os_family }}.yml"

# Add groups first so we can use them for our user(s)
- import_tasks: groups.yml
  tags:
    - users
    - users_groups
    - manage_groups
    - groups

# Then add user(s)
- import_tasks: users.yml
  tags:
    - users
    - manage_users

# Manage authorized keys for user(s)
- import_tasks: authorized_keys.yml
  tags:
    - users
    - manage_authorized_keys
