---

# Load a bit specific defaults
- name: Load OS specific values
  include_vars: "{{ lookup('first_found', params) }}"
  vars:
    params:
      files:
        - '{{ansible_distribution}}.yml'
        - '{{ansible_os_family}}.yml'
      paths:
        - 'vars'

# Add groups first so we can use them for our user(s)
- import_tasks: groups.yml
  tags:
    - users
    - users_groups
    - manage_groups
    - groups

# Then add user(s)
- import_tasks: users.yml
  tags:
    - users
    - manage_users

# Manage authorized keys for user(s)
- import_tasks: authorized_keys.yml
  tags:
    - users
    - manage_authorized_keys
