---

- name: Manage Users
  ansible.builtin.user:
    name: "{{ item.key }}"
    comment: "{{ item.value.comment | default(omit) }}"
    uid: "{{ item.value.uid | default(omit) }}"
    group: "{{ item.value.group | default(omit) }}"
    groups: "{{ item.value.groups | default([]) | join(',') }}"
    append: "{{ item.value.append | default(True) }}"
    state: "{{ item.value.state | default('present') }}"
    password: "{{ item.value.password | default(users_default_password) }}"
    update_password: "{{ item.value.update_password | default('on_create') }}"
    system: "{{ item.value.system | default(omit) }}"
    shell: "{{ item.value.shell | default(users_default_shell) }}"
    home: "{{ item.value.home | default(omit) }}"
    createhome: "{{ item.value.createhome | default(omit) }}"
    move_home: "{{ item.value.move_home | default(omit) }}"
    skeleton: "{{ item.value.skeleton | default(omit) }}"
    expires: "{{ item.value.expires | default(omit) }}"
    remove: "{{ item.value.remove | default(omit) }}"
    force: "{{ item.value.force | default(omit) }}"
    non_unique: "{{ item.value.non_unique | default(omit) }}"
    generate_ssh_key: "{{ item.value.generate_ssh_key | default(omit) }}"
    ssh_key_bits: "{{ item.value.ssh_key_bits | default(omit) }}"
    ssh_key_comment: "{{ item.value.ssh_key_comment | default(omit) }}"
    ssh_key_file: "{{ item.value.ssh_key_file | default(omit) }}"
    ssh_key_passphrase: "{{ item.value.ssh_key_passphrase | default(omit) }}"
    ssh_key_type: "{{ item.value.ssh_key_type | default(omit) }}"
  loop: "{{ users | dict2items }}"
  when:
    - item.key != 'root'
    - item.value.state is defined
    - (item.value.state == 'present' or item.value.state == 'absent')
  no_log: "{{ users_no_log | bool }}"
